unique_ids:
  assets:
    standard-page.html: 5M5X7SAPE3ZIDVWHV6Q7D47OEODI2Q6L
    theme.css: H275UU63TY5QFCDDDQNQX7PLQSAIOP3A
  forms:
    Form1: IE7LSAS44QPR3XAYDIM55O4H3GAKGRRH
  modules: {}
  scripts: {}
  server_modules: {}
